### PR TITLE
Added munki recipes and download recipes

### PR DESCRIPTION
**Pull request by charlesmisson**
Hey Graham, 

In my org we need to get the signed package instead of a repackaged tarball, I was tasked with making recipes that fit our needs, including the Munki ones.
We also need to support both HotSpot and OpenJ9.
This PR is contribute as others may need the same thing.

Let me know if you see any issue.

Thanks,
Charles

### CODE REVIEW

**Comment by grahampugh** [comment]
Hi Charles

Many thanks for all your work.

Really, I can't accept these in their current form into my own repo - they
are your work and should exist in your own repo. To include them into my
own repo, I would have to rename the identifiers to
com.github.grahampugh.recipes.... etc.

If you already have your own repo, you should add these recipes to it. You
can get a repo integrated into the AutoPkg fold using the information at
https://github.com/autopkg/autopkg/wiki/Sharing-Recipes (Note that I have
also done this in the past few days, so my local repo to which you have
submitted this PR is now for archive only).

However, if you don't want to maintain your own repo, I will integrate
these recipes into mine. I will have to change the recipe identifiers as
explained above, but I would add acknowledgement in the Descriptions of the
recipes and in the overall README that it was you who did the work.

Let me know which action you would prefer.

Cheers
Graham

**Comment by charlesmisson** [comment]
Hey Graham,

Having my own repo isn't an option, as we'd like to avoid having to maintain too much external repos, I'm fine with your second solution !

Thanks,
Charles

**Comment by grahampugh** [comment]
Hi Charles

OK, let me work on that, it won't be a straight PR merge due to the name
changes and I'll try and develop separate recipe structure for the signed
pkg and tar versions.  I'll let you know when it's in place.

Cheers
Graham

**Comment by grahampugh** [comment]
Merging into adopt branch for reconfiguration

**Comment by grahampugh** [comment]
Hi Charles

I've now added the recipes to my AutoPkg repo. They are now at https://github.com/autopkg/grahampugh-recipes/tree/master/AdoptOpenJDK

The identifiers are changed to my name and the Munki recipe identifiers include `_Signed` so it's clear which download recipe they are matching to. Please let me know if you test them, as I do not have a way of testing the Munki recipes.

Thanks again,
Graham

**Comment by grahampugh** [comment]
Hey Charles

Thanks a lot again for your work. You can now find the amended recipes at https://github.com/autopkg/grahampugh-recipes/tree/master/AdoptOpenJDK

Cheers
Graham

**Comment by grahampugh** [comment]
Hey Charles

Thanks a lot again for your work. You can now find the amended recipes at https://github.com/autopkg/grahampugh-recipes/tree/master/AdoptOpenJDK

Cheers
Graham

**Comment by grahampugh** [comment]
Hey Charles

Thanks a lot again for your work. You can now find the amended recipes at https://github.com/autopkg/grahampugh-recipes/tree/master/AdoptOpenJDK

Cheers
Graham

**Comment by grahampugh** [comment]
Hey Charles

Thanks a lot again for your work. You can now find the amended recipes at
https://github.com/autopkg/grahampugh-recipes/tree/master/AdoptOpenJDK

Please let me know if you test them. I can't test the Munki recipes without
setting up a Munki server for the sole purpose!

Cheers
Graham

**Comment by charlesmisson** [comment]
Thanks Graham, I have tested the updated recipes and they all work as intended.
Thanks again for moving so quickly, I'll finally be able to continue my internal work to deploy AdoptOpenJDK.

**Pull request merged**
